### ISSUE TITLE
Error: Missing accountUrl

### ISSUE THREAD

**Issue by shekhartupe** [AlisonVilela/ngx-zendesk-webwidget#3]
I followed exact steps mentioned in readme:

`import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';

import {ngxZendeskWebwidgetModule, ngxZendeskWebwidgetConfig} from 'ngx-zendesk-webwidget';

import {AppComponent} from './app';

export class ZendeskConfig extends ngxZendeskWebwidgetConfig {
  accountUrl: 'xxxxx.zendesk.com';
  beforePageLoad(zE: any) {
    zE.setLocale('en');
    zE.hide();
  };
}

@NgModule({
    imports: [
        BrowserModule,
        HttpClientModule,
        ngxZendeskWebwidgetModule.forRoot(ZendeskConfig)
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }`

Then init app

`import { ngxZendeskWebwidgetService } from 'ngx-zendesk-webwidget';

@Component({
  selector: 'app',
  templateUrl: './app.html'
})
export class app {

  constructor(private _ngxZendeskWebwidgetService: ngxZendeskWebwidgetService) {
  }
}`

Finally used

`_ngxZendeskWebwidgetService.show()`

But at app launch I get error:

`ERROR Error: Missing accountUrl. Please set in app config via ZendeskWidgetProvider
    at new ngxZendeskWebwidgetService (ngx-zendesk-webwidget.js:32)
    at AppModuleInjector.get (module.ngfactory.js? [sm]:1)
    at AppModuleInjector.getInternal (module.ngfactory.js? [sm]:1)
    at AppModuleInjector.NgModuleInjector.get (core.es5.js:3577)
    at resolveDep (core.es5.js:11039)
    at createClass (core.es5.js:10895)
    at createDirectiveInstance (core.es5.js:10723)
    at createViewNodes (core.es5.js:12086)
    at createRootView (core.es5.js:11991)
    at callWithDebugContext (core.es5.js:13206)
View_AppComponent_Host_0 @ AppComponent_Host.html:1
proxyClass @ compiler.es5.js:14091
DebugContext_.logError @ core.es5.js:13146
ErrorHandler.handleError @ core.es5.js:1144
(anonymous) @ core.es5.js:4684
ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.es5.js:4149
ZoneDelegate.invoke @ zone.js:390
Zone.run @ zone.js:141
(anonymous) @ zone.js:818
ZoneDelegate.invokeTask @ zone.js:424
onInvokeTask @ core.es5.js:4140
ZoneDelegate.invokeTask @ zone.js:423
Zone.runTask @ zone.js:191
drainMicroTaskQueue @ zone.js:584
Promise resolved (async)
scheduleMicroTask @ zone.js:567
ZoneDelegate.scheduleTask @ zone.js:413
Zone.scheduleTask @ zone.js:235
Zone.scheduleMicroTask @ zone.js:255
scheduleResolveOrReject @ zone.js:816
ZoneAwarePromise.then @ zone.js:905
ZoneAwarePromise.all @ zone.js:885
JitCompiler._loadModules @ compiler.es5.js:25638
JitCompiler._compileModuleAndComponents @ compiler.es5.js:25589
JitCompiler.compileModuleAsync @ compiler.es5.js:25551
PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4811
PlatformRef_.bootstrapModule @ core.es5.js:4797
c @ main.ts:11
__webpack_require__ @ bootstrap 2f077470391ccc3fd8c7:52
(anonymous) @ main.bundle.js:4257
__webpack_require__ @ bootstrap 2f077470391ccc3fd8c7:52
webpackJsonpCallback @ bootstrap 2f077470391ccc3fd8c7:23
(anonymous) @ main.bundle.js:1
AppComponent_Host.html:1 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 1, nodeDef: {…}, elDef: {…}, elView: {…}}
View_AppComponent_Host_0 @ AppComponent_Host.html:1
proxyClass @ compiler.es5.js:14091
DebugContext_.logError @ core.es5.js:13146
ErrorHandler.handleError @ core.es5.js:1149
(anonymous) @ core.es5.js:4684
ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.es5.js:4149
ZoneDelegate.invoke @ zone.js:390
Zone.run @ zone.js:141
(anonymous) @ zone.js:818
ZoneDelegate.invokeTask @ zone.js:424
onInvokeTask @ core.es5.js:4140
ZoneDelegate.invokeTask @ zone.js:423
Zone.runTask @ zone.js:191
drainMicroTaskQueue @ zone.js:584
Promise resolved (async)
scheduleMicroTask @ zone.js:567
ZoneDelegate.scheduleTask @ zone.js:413
Zone.scheduleTask @ zone.js:235
Zone.scheduleMicroTask @ zone.js:255
scheduleResolveOrReject @ zone.js:816
ZoneAwarePromise.then @ zone.js:905
ZoneAwarePromise.all @ zone.js:885
JitCompiler._loadModules @ compiler.es5.js:25638
JitCompiler._compileModuleAndComponents @ compiler.es5.js:25589
JitCompiler.compileModuleAsync @ compiler.es5.js:25551
PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4811
PlatformRef_.bootstrapModule @ core.es5.js:4797
c @ main.ts:11
__webpack_require__ @ bootstrap 2f077470391ccc3fd8c7:52
(anonymous) @ main.bundle.js:4257
__webpack_require__ @ bootstrap 2f077470391ccc3fd8c7:52
webpackJsonpCallback @ bootstrap 2f077470391ccc3fd8c7:23
(anonymous) @ main.bundle.js:1
zone.js:643 Unhandled Promise rejection: Missing accountUrl. Please set in app config via ZendeskWidgetProvider ; Zone: <root> ; Task: Promise.then ; Value: Error: Missing accountUrl. Please set in app config via ZendeskWidgetProvider
    at new ngxZendeskWebwidgetService (ngx-zendesk-webwidget.js:32)
    at AppModuleInjector.get (module.ngfactory.js? [sm]:1)
    at AppModuleInjector.getInternal (module.ngfactory.js? [sm]:1)
    at AppModuleInjector.NgModuleInjector.get (core.es5.js:3577)
    at resolveDep (core.es5.js:11039)
    at createClass (core.es5.js:10895)
    at createDirectiveInstance (core.es5.js:10723)
    at createViewNodes (core.es5.js:12086)
    at createRootView (core.es5.js:11991)
    at callWithDebugContext (core.es5.js:13206) Error: Missing accountUrl. Please set in app config via ZendeskWidgetProvider
    at new ngxZendeskWebwidgetService (http://localhost:4200/vendor.bundle.js:35452:19)
    at AppModuleInjector.get (ng:///AppModule/module.ngfactory.js:234:97)
    at AppModuleInjector.getInternal (ng:///AppModule/module.ngfactory.js:489:67)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:4200/vendor.bundle.js:3788:44)
    at resolveDep (http://localhost:4200/vendor.bundle.js:11250:45)
    at createClass (http://localhost:4200/vendor.bundle.js:11106:91)
    at createDirectiveInstance (http://localhost:4200/vendor.bundle.js:10934:37)
    at createViewNodes (http://localhost:4200/vendor.bundle.js:12297:49)
    at createRootView (http://localhost:4200/vendor.bundle.js:12202:5)
    at callWithDebugContext (http://localhost:4200/vendor.bundle.js:13417:42)
api.onUnhandledError @ zone.js:643
handleUnhandledRejection @ zone.js:667
_loop_1 @ zone.js:658
api.microtaskDrainDone @ zone.js:662
drainMicroTaskQueue @ zone.js:592
Promise resolved (async)
scheduleMicroTask @ zone.js:567
ZoneDelegate.scheduleTask @ zone.js:413
Zone.scheduleTask @ zone.js:235
Zone.scheduleMicroTask @ zone.js:255
scheduleResolveOrReject @ zone.js:816
ZoneAwarePromise.then @ zone.js:905
ZoneAwarePromise.all @ zone.js:885
JitCompiler._loadModules @ compiler.es5.js:25638
JitCompiler._compileModuleAndComponents @ compiler.es5.js:25589
JitCompiler.compileModuleAsync @ compiler.es5.js:25551
PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4811
PlatformRef_.bootstrapModule @ core.es5.js:4797
c @ main.ts:11
__webpack_require__ @ bootstrap 2f077470391ccc3fd8c7:52
(anonymous) @ main.bundle.js:4257
__webpack_require__ @ bootstrap 2f077470391ccc3fd8c7:52
webpackJsonpCallback @ bootstrap 2f077470391ccc3fd8c7:23
(anonymous) @ main.bundle.js:1
zone.js:645 Error: Uncaught (in promise): Error: Missing accountUrl. Please set in app config via ZendeskWidgetProvider
Error: Missing accountUrl. Please set in app config via ZendeskWidgetProvider
    at new ngxZendeskWebwidgetService (ngx-zendesk-webwidget.js:32)
    at AppModuleInjector.get (module.ngfactory.js? [sm]:1)
    at AppModuleInjector.getInternal (module.ngfactory.js? [sm]:1)
    at AppModuleInjector.NgModuleInjector.get (core.es5.js:3577)
    at resolveDep (core.es5.js:11039)
    at createClass (core.es5.js:10895)
    at createDirectiveInstance (core.es5.js:10723)
    at createViewNodes (core.es5.js:12086)
    at createRootView (core.es5.js:11991)
    at callWithDebugContext (core.es5.js:13206)
    at new ngxZendeskWebwidgetService (ngx-zendesk-webwidget.js:32)
    at AppModuleInjector.get (module.ngfactory.js? [sm]:1)
    at AppModuleInjector.getInternal (module.ngfactory.js? [sm]:1)
    at AppModuleInjector.NgModuleInjector.get (core.es5.js:3577)
    at resolveDep (core.es5.js:11039)
    at createClass (core.es5.js:10895)
    at createDirectiveInstance (core.es5.js:10723)
    at createViewNodes (core.es5.js:12086)
    at createRootView (core.es5.js:11991)
    at callWithDebugContext (core.es5.js:13206)
    at resolvePromise (zone.js:770)
    at zone.js:696
    at zone.js:712
    at ZoneDelegate.invoke (zone.js:391)
    at Zone.run (zone.js:141)
    at zone.js:818
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:191)
    at drainMicroTaskQueue (zone.js:584)
    at <anonymous>`

Any insights ?

**Comment by AlisonVilela** [comment]
@NgModule({
imports: [
    BrowserModule,
    HttpClientModule,
    ngxZendeskWebwidgetModule.forRoot(ZendeskConfig)
],
bootstrap: [AppComponent]
})
export class AppModule { }

Where are you importing the `app`?

**Comment by shekhartupe** [comment]
In app.module.ts under @NgModule -> imports

**Comment by AlisonVilela** [comment]
declarations: [
    AppComponent
]


And in your `AppComponent`

@component({
selector: 'app-root',
templateUrl: './app.component.html'
})
export class AppComponent {

constructor(private _ngxZendeskWebwidgetService: ngxZendeskWebwidgetService) {
}
}`

**Comment by shekhartupe** [comment]
Yes, declarations has AppComponent in app.module.ts

@NgModule({
  declarations: [
    AppComponent,

And AppComponent constructor has,

constructor(translate: TranslateService, 
     private ngxZendeskWebwidgetService: ngxZendeskWebwidgetService) {

**Comment by shekhartupe** [comment]
Hi @AlisonVilela, any insights ? Or if you have a working demo app, will help.

**Comment by jerojasol** [comment]
Hi @AlisonVilela and @shekhartupe I have the same error, you found the solution?, this is the error:

core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: Missing accountUrl. Please set in app config via ZendeskWidgetProvider
Error: Missing accountUrl. Please set in app config via ZendeskWidgetProvider
    at new ngxZendeskWebwidgetService (ngx-zendesk-webwidget.js:32)
    at _createClass (core.es5.js:9512)
    at _createProviderInstance$1 (core.es5.js:9484)
    at resolveNgModuleDep (core.es5.js:9469)
    at NgModuleRef_.get (core.es5.js:10555)
    at resolveNgModuleDep (core.es5.js:9473)
    at NgModuleRef_.get (core.es5.js:10555)
    at resolveDep (core.es5.js:11058)
    at createClass (core.es5.js:10922)
    at createDirectiveInstance (core.es5.js:10742)
    at new ngxZendeskWebwidgetService (ngx-zendesk-webwidget.js:32)
    at _createClass (core.es5.js:9512)
    at _createProviderInstance$1 (core.es5.js:9484)
    at resolveNgModuleDep (core.es5.js:9469)
    at NgModuleRef_.get (core.es5.js:10555)
    at resolveNgModuleDep (core.es5.js:9473)
    at NgModuleRef_.get (core.es5.js:10555)
    at resolveDep (core.es5.js:11058)
    at createClass (core.es5.js:10922)
    at createDirectiveInstance (core.es5.js:10742)
    at resolvePromise (zone.js:783)
    at resolvePromise (zone.js:754)
    at eval (zone.js:831)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Object.onInvokeTask (core.es5.js:3881)
    at ZoneDelegate.invokeTask (zone.js:423)
    at Zone.runTask (zone.js:191)
    at drainMicroTaskQueue (zone.js:595)
    at ZoneTask.invokeTask [as invoke] (zone.js:502)
    at invokeTask (zone.js:1364)
___________________________________________________
in app.module.ts I have:

export class ZendeskConfig extends ngxZendeskWebwidgetConfig {

    accountUrl: '--myaccount--.zendesk.com';

    beforePageLoad(zE: any): void {
        zE.setLocale('en');
        zE.hide();
    }
}

@NgModule({
imports: [
ngxZendeskWebwidgetModule.forRoot(ZendeskConfig), ...

_________________________________________________
in my component I have:

constructor(
  private _ngxZendeskWebwidgetService: ngxZendeskWebwidgetService...

thank you.

**Comment by AlisonVilela** [comment]
Can you reproduce this error at http://plnkr.co or another equivalent?

**Comment by shekhartupe** [comment]
@AlisonVilela - I am attaching sample angular 2 app with above configurations. When you run the app you can see the error.
[zendesk-integration-app.zip](https://github.com/AlisonVilela/ngx-zendesk-webwidget/files/1648941/zendesk-integration-app.zip)

**Comment by Gnorro** [comment]
same error:
Missing accountUrl. Please set in app config via ZendeskWidgetProvider
    at new ngxZendeskWebwidgetService (ngx-zendesk-webwidget.js:32)

**Comment by AlisonVilela** [comment]
@shekhartupe Okay, thanks, I'll test and see what's going wrong, I'll be back shortly with some response

**Comment by AlisonVilela** [comment]
@shekhartupe

Your configuration.:
` accountUrl: 'myaccount.zendesk.com';`

Correct configuration.: 
` accountUrl = 'myaccount.zendesk.com';`

I'll update README

Thank you!

**Comment by shekhartupe** [comment]
Thanks @AlisonVilela. It fixed the issue and I see the widget on my Angular app. Appreciate your help.

**Comment by Gnorro** [comment]
it works, thanks

But zE.hide() doesn't work for me, in the sense that widget is always visible. if I use .activate() it works, it opens widget.

I have a question about how to open widget. I would like to activate widget only if a specific parameter is passed to application, for example:
http://www.mysite.com?chat=1

in my app.component i can get that parameter, but then, how can interact with widget configuration in order to activate it?

thanks
